name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      id: test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: 'apt-get update ; apt-get -y install wget ; wget -O galaxy_test.h5
          "https://www.dropbox.com/scl/fi/5fh5xlqu4nhtwgq9kvqtv/galaxy_test.h5?rlkey=sjdwic2lls7m6xuvtljycfzx6&dl=1"
          ;  pip3 install -r requirements.txt '
    - name: performance test
      id: performance-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: performance test
        setup-command: 'apt-get update ; apt-get -y install wget ; wget -O galaxy_test.h5
          "https://www.dropbox.com/scl/fi/5fh5xlqu4nhtwgq9kvqtv/galaxy_test.h5?rlkey=sjdwic2lls7m6xuvtljycfzx6&dl=1"
          ;  pip3 install -r requirements.txt '
        command: pytest
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
        PERFORMANCE-TEST_RESULTS: "${{steps.performance-test.outputs.result}}"
      with:
        runners: test,performance-test
